sudo: required
services:
  - docker

before_install:
  - docker build -t cutening/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true cutening/react-test npm test

# after pass test
after_success:
  - docker build -t cutening/multi-client ./client
  - docker build -t cutening/multi-worker ./worker
  - docker build -t cutening/multi-server ./server
  - docker build -t cutening/multi-nginx ./nginx
  # log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those iamges and push docker hub
  - docker push cutening/multi-client
  - docker push cutening/multi-server
  - docker push cutening/multi-worker
  - docker push cutening/multi-nginx
